wandb_version: 1

domain_name:
  desc: null
  value: walker
task_name:
  desc: null
  value: walk
frame_stack:
  desc: null
  value: 3
action_repeat:
  desc: null
  value: 2
episode_length:
  desc: null
  value: 1000
eval_mode:
  desc: null
  value: video_hard
algorithm:
  desc: null
  value: svea
train_steps:
  desc: null
  value: 250000
discount:
  desc: null
  value: 0.99
init_steps:
  desc: null
  value: 1000
batch_size:
  desc: null
  value: 128
hidden_dim:
  desc: null
  value: 1024
actor_lr:
  desc: null
  value: 0.001
actor_beta:
  desc: null
  value: 0.9
actor_log_std_min:
  desc: null
  value: -10
actor_log_std_max:
  desc: null
  value: 2
actor_update_freq:
  desc: null
  value: 2
critic_lr:
  desc: null
  value: 0.001
critic_beta:
  desc: null
  value: 0.9
critic_tau:
  desc: null
  value: 0.01
critic_target_update_freq:
  desc: null
  value: 2
num_shared_layers:
  desc: null
  value: 11
num_head_layers:
  desc: null
  value: 0
num_filters:
  desc: null
  value: 32
projection_dim:
  desc: null
  value: 100
encoder_tau:
  desc: null
  value: 0.05
init_temperature:
  desc: null
  value: 0.1
alpha_lr:
  desc: null
  value: 0.0001
alpha_beta:
  desc: null
  value: 0.5
aux_lr:
  desc: null
  value: 0.001
aux_beta:
  desc: null
  value: 0.9
aux_update_freq:
  desc: null
  value: 2
soda_batch_size:
  desc: null
  value: 256
soda_tau:
  desc: null
  value: 0.005
svea_alpha:
  desc: null
  value: 0.5
svea_beta:
  desc: null
  value: 0.5
save_freq:
  desc: null
  value: 100000
eval_freq:
  desc: null
  value: 10000
eval_episodes:
  desc: null
  value: 30
distracting_cs_intensity:
  desc: null
  value: 0.0
seed:
  desc: null
  value: 1
log_dir:
  desc: null
  value: logs
save_video:
  desc: null
  value: false
image_size:
  desc: null
  value: 84
image_crop_size:
  desc: null
  value: 84
env:
  desc: null
  value:
    domain: walker
    task: walk
group_name:
  desc: null
  value: Hansen_repo
exp_name:
  desc: null
  value: vanilla_svea_randomoverlay
hard_aug_type:
  desc: null
  value: random_overlay
_wandb:
  desc: null
  value:
    python_version: 3.7.6
    cli_version: 0.15.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693914947.775185
    t:
      1:
      - 1
      - 41
      - 55
      - 79
      2:
      - 1
      - 41
      - 55
      - 79
      3:
      - 16
      - 23
      4: 3.7.6
      5: 0.15.9
      8:
      - 8
